= Windows 9x Registry File (CREG) format specification
Analysis of the 9x Registry file format

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

A Windows 9x/Me Registry File is used by Microsoft Windows 95, 98 and Me tog
store a part of the Windows Registry. This specification is based on earlierg
work on the format and was complimented by reverse engineering.

This document is intended as a working document for the Windows 9x/Me Registryg
File (CREG) format specification. Which should allow existing Open Sourceg
forensic tooling to be able to process this file type.

Special thanks to unknown author B.D. for his work on the format.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the Windows 9x Registry File format.
| Classification: | Public
| Keywords: | Windows Registry File, CREG
|===

[preface]
== License

....
Copyright (C) 2009-2020, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under theg
terms of the GNU Free Documentation License, Version 1.3 or any later versiong
published by the Free Software Foundation; with no Invariant Sections, nog
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is includedg
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | July 2009 | Initial version.
| 0.0.2 | J.B. Metz | February 2013 | Updated license version and email address.
| 0.0.3 | J.B. Metz | June 2013 | Minor changes.
| 0.0.4 | J.B. Metz | November 2015 | Switched to asccidoc format.
| 0.0.5 | J.B. Metz | January 2016 | Additional changes.
| 0.0.6 | J.B. Metz | January 2020 | Formatting changes.
|===

:numbered:
== Overview

A Windows Registry File 9x/Me (CREG) is used by Microsoft Windows 95, 98 and Meg
to store a part of the Windows Registry. These parts are also referred to asg
hives.

A CREG consist of the following distinguishable elements:

* file header
* Registry Key Navigation record
** Registry key hierarchy entries
* Registry data blocks
** Registry key value entries

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values |g
| Character strings |g
|===

=== Test version

The following version of programs were used to test the information within thisg
document:

* Windows 95
* Windows 98
* [yellow-background]*TODO: Windows Me*
* [yellow-background]*TODO: Windows NT 3.5*

=== Registy files

Some of the more common Registry files are:

[cols="1,1,5",options="header"]
|===
| Windows version | Filename | Description
| Me | CLASSES.DAT |
| 95, 98 | POLICY.POL | System policies specific part of the Registry +
Location: %SystemRoot%\ +
This file is optional
| 95, 98 | SYSTEM.DAT | System specific part of the Registry +
Location: %SystemRoot%\ +
Registry key: HKEY_LOCAL_MACHINE
| 95 | SYSTEM.DAO | Backup of SYSTEM.DAT
| 95, 98 | USER.DAT | User specific part of the Registry +
Location: %SystemRoot%\ +
Registry key: HKEY_USERS
| 95 | USER.DAO | Backup of USER.DAT
|===

== File header

The file header is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "CREG" | The signature
| 4 | 2 | 0 | Minor format version
| 6 | 2 | 1 | Major format version
| 8 | 4 | | Data blocks list offset* +
The offset is relative to the start of the file
| 12 | 4 | | [yellow-background]*Unknown (checksum? Fat date time?)*
| 16 | 2 | | [yellow-background]*Unknown*
| 18 | 2 | | Number of Registry data blocks
| 20 | 2 | | [yellow-background]*Unknown (Copy of minor version?)*
| 22 | 2 | | [yellow-background]*Unknown (Copy of major version?)*
| 24 | 8 | | [yellow-background]*Unknown (empty values)*
|===

== Registry Key Navigation

The Registry Key Navigation consists of:

* Registry Key Navigation record
* Key hierarchy entries area

[NOTE]
The key hierarchy entries are stored unaligned within the area.

=== Registry Key Navigation record

The Registry Key Navigation record is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "RGKN" | The signature
| 4 | 4 | | Size +
The Registry Key Navigation record including the 4 bytes of the signature and 4 bytes of the size itself
| 8 | 4 | | Key hierarchy entries data offset +
The offset is relative from the start of the Registry Key Navigation record
| 12 | 4 | | Key hierarchy entries data size +
The size does not contain the size of the root (first) key hierarcy entry
| 16 | 4 | | [yellow-background]*Unknown*
| 20 | 4 | | [yellow-background]*Unknown (Checksum?)*
| 24 | 8 | | [yellow-background]*Unknown (empty values)*
|===

=== Key hierarchy entry

A key hierarchy entry contain the structural information of a Registry key.

The key record entry is 28 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Seen 0 and -1 (0xffffffff)*
| 4 | 4 | | The hash of the key name
| 8 | 4 | | [yellow-background]*Unknown reference* +
[yellow-background]*or -1 (0xffffffff) if the value is not set (end of list)*
| 12 | 4 | | Parent key offset +
The offset is relative from the start of the Registry Key Navigation record or -1 (0xffffffff) if the value is not set
| 16 | 4 | | First sub key offset +
The offset is relative from the start of the Registry Key Navigation record or -1 (0xffffffff) if the value is not set
| 20 | 4 | | Next key offset +
The offset is relative from the start of the Registry Key Navigation record or -1 (0xffffffff) if the value is not set
| 24 | 2 | | Key name entry number +
The number of the key name entry, starting with 0, within a data block the corresponding key name entry is stored or -1 (0xffff) if the value is not set +
[yellow-background]*Does this value contain flags 0x1000?*
| 26 | 2 | | Data block number +
The number of the data block, starting with 0, the corresponding key name entry is stored or -1 (0xffff) if the value is not set
|===

[yellow-background]*The first key record entry refers to its own key record.*

=== Hashing method

If you have the key name:
....
Software\Microsoft
....

A hash is determined per part of the key. The parts of the key are separated byg
the backslash character. A separate part of the key is first changed intog
uppercase. So the keys are case insensitive.
....
SOFTWARE
....

Every character value in the key part is added to each other:
....
hash_value = 0;

for ( key_part_index = 0;
      key_part_index < key_part_length;
      key_part_index++ )
{
    if( key_part[ key_part_index ] < 0x80 )
    {
        hash_value += key_part[ key_part_index ];
    }
}
....

....
SOFTWARE => 0x026b
....

== Registry data block

The registry data block (RGDB) is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | "RGDB" | The signature
| 4 | 4 | | Size +
The size of the Registry data block including the 8 bytes of the the signature and size
| 8 | 4 | | Unused size
| 12 | 2 | | [yellow-background]*Unknown (flags?)* +
[yellow-background]*Seen 0x0008*
| 14 | 2 | | Index
| 16 | 4 | | Used size +
[yellow-background]*Does -1 (0xffffffff) represent the data block is allowed to grow?*
| 20 | 2 | | [yellow-background]*Unknown (related to number of entries?)*
| 22 | 2 | | [yellow-background]*Unknown (related to number of entries?)*
| 24 | 8 | | [yellow-background]*Unknown (remnant data?)*
|===

=== Key name entry

The key name entries contain the Registry keys.

The key name entry is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Size +
The size of the key name entry including the 4 bytes of the size
| 4 | 2 | | Index
| 6 | 2 | | [yellow-background]*Unknown* +
[yellow-background]*Seen: 0x0000, 0x00.. and 0xffff*
| 8 | 4 | | Used size
| 12 | 2 | | Name size
| 14 | 2 | | Number of values
| 16 | 4 | | [yellow-background]*Unknown (Empty values)*
| 20 | ... | | Name string +
Contains an ASCII string which is not terminated by an end-of-string character
| ... | ... | | Values data
| ... | ... | | [yellow-background]*Unknown* +
Can contain remnant data
|===

=== Value entry

The value entries contain the of Registry key value.

The value entry is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Data type
| 4 | 4 | | [yellow-background]*Unknown (Empty values)*
| 8 | 2 | | Name size
| 10 | 2 | | Data size
| 12 | ... | | Name string +
Contains an ASCII string which is not terminated by an end-of-string character
| ... | ... | | Data
|===

=== Data types

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00000001 | RegSZ | String +
[yellow-background]*(sometimes the end-of-string character is not included)*
| | |
| 0x00000003 | RegBin | Binary Data
| 0x00000004 | RegDWord | 32-bit integer (double word)
|===

== Notes

....
libcreg_key_name_entry_read: data:
00000000: 2f 00 00 00 ff ff ff ff  5f 7b 00 00 0f 00 01 00   /....... _{......
00000010: 00 00 00 00 43 6f 6e 74  72 6f 6c 73 20 46 6f 6c   ....Cont rols Fol
00000020: 64 65 72 01 00 00 00 ff  ff ff ff 00 00 00 00      der..... .......

libcreg_key_name_entry_read: size                                       : 47
libcreg_key_name_entry_read: index                                      : 65535
libcreg_key_name_entry_read: unknown1                                   : 0xffff
libcreg_key_name_entry_read: used size                                  : 31583
libcreg_key_name_entry_read: name size                                  : 15
libcreg_key_name_entry_read: number of values                           : 1
libcreg_key_name_entry_read: unknown2                                   : 0x00000000

Are unknown1 (0xffff) and strange used size related some how?
....

:numbered!:
[appendix]
== References

`[WINREG]`

[cols="1,5",options="header"]
|===
| Title: | WinReg.txt
| Author(s): | B.D.
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.g
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this licenseg
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functionalg
and useful document "free" in the sense of freedom: to assure everyone theg
effective freedom to copy and redistribute it, with or without modifying it,g
either commercially or noncommercially. Secondarily, this License preserves forg
the author and publisher a way to get credit for their work, while not beingg
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of theg
document must themselves be free in the same sense. It complements the GNUg
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,g
because free software needs free documentation: a free program should come withg
manuals providing the same freedoms that the software does. But this License isg
not limited to software manuals; it can be used for any textual work,g
regardless of subject matter or whether it is published as a printed book. Weg
recommend this License principally for works whose purpose is instruction org
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that containsg
a notice placed by the copyright holder saying it can be distributed under theg
terms of this License. Such a notice grants a world-wide, royalty-free license,g
unlimited in duration, to use that work under the conditions stated herein. Theg
"Document", below, refers to any such manual or work. Any member of the publicg
is a licensee, and is addressed as "you". You accept the license if you copy,g
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document org
a portion of it, either copied verbatim, or with modifications and/org
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of theg
Document that deals exclusively with the relationship of the publishers org
authors of the Document to the Document's overall subject (or to relatedg
matters) and contains nothing that could fall directly within that overallg
subject. (Thus, if the Document is in part a textbook of mathematics, ag
Secondary Section may not explain any mathematics.) The relationship could be ag
matter of historical connection with the subject or with related matters, or ofg
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles areg
designated, as being those of Invariant Sections, in the notice that says thatg
the Document is released under this License. If a section does not fit theg
above definition of Secondary then it is not allowed to be designated asg
Invariant. The Document may contain zero Invariant Sections. If the Documentg
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, asg
Front-Cover Texts or Back-Cover Texts, in the notice that says that theg
Document is released under this License. A Front-Cover Text may be at most 5g
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, representedg
in a format whose specification is available to the general public, that isg
suitable for revising the document straightforwardly with generic text editorsg
or (for images composed of pixels) generic paint programs or (for drawings)g
some widely available drawing editor, and that is suitable for input to textg
formatters or for automatic translation to a variety of formats suitable forg
input to text formatters. A copy made in an otherwise Transparent file formatg
whose markup, or absence of markup, has been arranged to thwart or discourageg
subsequent modification by readers is not Transparent. An image format is notg
Transparent if used for any substantial amount of text. A copy that is notg
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII withoutg
markup, Texinfo input format, LaTeX input format, SGML or XML using a publiclyg
available DTD, and standard-conforming simple HTML, PostScript or PDF designedg
for human modification. Examples of transparent image formats include PNG, XCFg
and JPG. Opaque formats include proprietary formats that can be read and editedg
only by proprietary word processors, SGML or XML for which the DTD and/org
processing tools are not generally available, and the machine-generated HTML,g
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus suchg
following pages as are needed to hold, legibly, the material this Licenseg
requires to appear in the title page. For works in formats which do not haveg
any title page as such, "Title Page" means the text near the most prominentg
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of theg
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose titleg
either is precisely XYZ or contains XYZ in parentheses following text thatg
translates XYZ in another language. (Here XYZ stands for a specific sectiong
name mentioned below, such as "Acknowledgements", "Dedications",g
"Endorsements", or "History".) To "Preserve the Title" of such a section wheng
you modify the Document means that it remains a section "Entitled XYZ"g
according to this definition.

The Document may include Warranty Disclaimers next to the notice which statesg
that this License applies to the Document. These Warranty Disclaimers areg
considered to be included by reference in this License, but only as regardsg
disclaiming warranties: any other implication that these Warranty Disclaimersg
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially org
noncommercially, provided that this License, the copyright notices, and theg
license notice saying this License applies to the Document are reproduced ing
all copies, and that you add no other conditions whatsoever to those of thisg
License. You may not use technical measures to obstruct or control the readingg
or further copying of the copies you make or distribute. However, you mayg
accept compensation in exchange for copies. If you distribute a large enoughg
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you mayg
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printedg
covers) of the Document, numbering more than 100, and the Document's licenseg
notice requires Cover Texts, you must enclose the copies in covers that carry,g
clearly and legibly, all these Cover Texts: Front-Cover Texts on the frontg
cover, and Back-Cover Texts on the back cover. Both covers must also clearlyg
and legibly identify you as the publisher of these copies. The front cover mustg
present the full title with all words of the title equally prominent andg
visible. You may add other material on the covers in addition. Copying withg
changes limited to the covers, as long as they preserve the title of theg
Document and satisfy these conditions, can be treated as verbatim copying ing
other respects.

If the required texts for either cover are too voluminous to fit legibly, youg
should put the first ones listed (as many as fit reasonably) on the actualg
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more thang
100, you must either include a machine-readable Transparent copy along withg
each Opaque copy, or state in or with each Opaque copy a computer-networkg
location from which the general network-using public has access to downloadg
using public-standard network protocols a complete Transparent copy of theg
Document, free of added material. If you use the latter option, you must takeg
reasonably prudent steps, when you begin distribution of Opaque copies ing
quantity, to ensure that this Transparent copy will remain thus accessible atg
the stated location until at least one year after the last time you distributeg
an Opaque copy (directly or through your agents or retailers) of that editiong
to the public.

It is requested, but not required, that you contact the authors of the Documentg
well before redistributing any large number of copies, to give them a chance tog
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under theg
conditions of sections 2 and 3 above, provided that you release the Modifiedg
Version under precisely this License, with the Modified Version filling theg
role of the Document, thus licensing distribution and modification of theg
Modified Version to whoever possesses a copy of it. In addition, you must dog
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from thatg
of the Document, and from those of previous versions (which should, if thereg
were any, be listed in the History section of the Document). You may use theg
same title as a previous version if the original publisher of that versiong
gives permission.g

B. List on the Title Page, as authors, one or more persons or entitiesg
responsible for authorship of the modifications in the Modified Version,g
together with at least five of the principal authors of the Document (all ofg
its principal authors, if it has fewer than five), unless they release you fromg
this requirement.g

C. State on the Title page the name of the publisher of the Modified Version,g
as the publisher.g

D. Preserve all the copyright notices of the Document.g

E. Add an appropriate copyright notice for your modifications adjacent to theg
other copyright notices.g

F. Include, immediately after the copyright notices, a license notice givingg
the public permission to use the Modified Version under the terms of thisg
License, in the form shown in the Addendum below.g

G. Preserve in that license notice the full lists of Invariant Sections andg
required Cover Texts given in the Document's license notice.g

H. Include an unaltered copy of this License.g

I. Preserve the section Entitled "History", Preserve its Title, and add to itg
an item stating at least the title, year, new authors, and publisher of theg
Modified Version as given on the Title Page. If there is no section Entitledg
"History" in the Document, create one stating the title, year, authors, andg
publisher of the Document as given on its Title Page, then add an itemg
describing the Modified Version as stated in the previous sentence.g

J. Preserve the network location, if any, given in the Document for publicg
access to a Transparent copy of the Document, and likewise the networkg
locations given in the Document for previous versions it was based on. Theseg
may be placed in the "History" section. You may omit a network location for ag
work that was published at least four years before the Document itself, or ifg
the original publisher of the version it refers to gives permission.g

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve theg
Title of the section, and preserve in the section all the substance and tone ofg
each of the contributor acknowledgements and/or dedications given therein.g

L. Preserve all the Invariant Sections of the Document, unaltered in their textg
and in their titles. Section numbers or the equivalent are not considered partg
of the section titles.g

M. Delete any section Entitled "Endorsements". Such a section may not beg
included in the Modified Version.g

N. Do not retitle any existing section to be Entitled "Endorsements" or tog
conflict in title with any Invariant Section.g

O. Preserve any Warranty Disclaimers.g

If the Modified Version includes new front-matter sections or appendices thatg
qualify as Secondary Sections and contain no material copied from the Document,g
you may at your option designate some or all of these sections as invariant. Tog
do this, add their titles to the list of Invariant Sections in the Modifiedg
Version's license notice. These titles must be distinct from any other sectiong
titles.

You may add a section Entitled "Endorsements", provided it contains nothing butg
endorsements of your Modified Version by various parties—for example,g
statements of peer review or that the text has been approved by an organizationg
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passageg
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Textsg
in the Modified Version. Only one passage of Front-Cover Text and one ofg
Back-Cover Text may be added by (or through arrangements made by) any oneg
entity. If the Document already includes a cover text for the same cover,g
previously added by you or by arrangement made by the same entity you areg
acting on behalf of, you may not add another; but you may replace the old one,g
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License giveg
permission to use their names for publicity for or to assert or implyg
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,g
under the terms defined in section 4 above for modified versions, provided thatg
you include in the combination all of the Invariant Sections of all of theg
original documents, unmodified, and list them all as Invariant Sections of yourg
combined work in its license notice, and that you preserve all their Warrantyg
Disclaimers.

The combined work need only contain one copy of this License, and multipleg
identical Invariant Sections may be replaced with a single copy. If there areg
multiple Invariant Sections with the same name but different contents, make theg
title of each such section unique by adding at the end of it, in parentheses,g
the name of the original author or publisher of that section if known, or elseg
a unique number. Make the same adjustment to the section titles in the list ofg
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in theg
various original documents, forming one section Entitled "History"; likewiseg
combine any sections Entitled "Acknowledgements", and any sections Entitledg
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documentsg
released under this License, and replace the individual copies of this Licenseg
in the various documents with a single copy that is included in the collection,g
provided that you follow the rules of this License for verbatim copying of eachg
of the documents in all other respects.

You may extract a single document from such a collection, and distribute itg
individually under this License, provided you insert a copy of this Licenseg
into the extracted document, and follow this License in all other respectsg
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate andg
independent documents or works, in or on a volume of a storage or distributiong
medium, is called an "aggregate" if the copyright resulting from theg
compilation is not used to limit the legal rights of the compilation's usersg
beyond what the individual works permit. When the Document is included in ang
aggregate, this License does not apply to the other works in the aggregateg
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of theg
Document, then if the Document is less than one half of the entire aggregate,g
the Document's Cover Texts may be placed on covers that bracket the Documentg
within the aggregate, or the electronic equivalent of covers if the Document isg
in electronic form. Otherwise they must appear on printed covers that bracketg
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distributeg
translations of the Document under the terms of section 4. Replacing Invariantg
Sections with translations requires special permission from their copyrightg
holders, but you may include translations of some or all Invariant Sections ing
addition to the original versions of these Invariant Sections. You may includeg
a translation of this License, and all the license notices in the Document, andg
any Warranty Disclaimers, provided that you also include the original Englishg
version of this License and the original versions of those notices andg
disclaimers. In case of a disagreement between the translation and the originalg
version of this License or a notice or disclaimer, the original version willg
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", org
"History", the requirement (section 4) to Preserve its Title (section 1) willg
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except asg
expressly provided under this License. Any attempt otherwise to copy, modify,g
sublicense, or distribute it is void, and will automatically terminate yourg
rights under this License.

However, if you cease all violation of this License, then your license from ag
particular copyright holder is reinstated (a) provisionally, unless and untilg
the copyright holder explicitly and finally terminates your license, and (b)g
permanently, if the copyright holder fails to notify you of the violation byg
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstatedg
permanently if the copyright holder notifies you of the violation by someg
reasonable means, this is the first time you have received notice of violationg
of this License (for any work) from that copyright holder, and you cure theg
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licensesg
of parties who have received copies or rights from you under this License. Ifg
your rights have been terminated and not permanently reinstated, receipt of ag
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Freeg
Documentation License from time to time. Such new versions will be similar ing
spirit to the present version, but may differ in detail to address new problemsg
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If theg
Document specifies that a particular numbered version of this License "or anyg
later version" applies to it, you have the option of following the terms andg
conditions either of that specified version or of any later version that hasg
been published (not as a draft) by the Free Software Foundation. If theg
Document does not specify a version number of this License, you may choose anyg
version ever published (not as a draft) by the Free Software Foundation. If theg
Document specifies that a proxy can decide which future versions of thisg
License can be used, that proxy's public statement of acceptance of a versiong
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wideg
Web server that publishes copyrightable works and also provides prominentg
facilities for anybody to edit those works. A public wiki that anybody can editg
is an example of such a server. A "Massive Multiauthor Collaboration" (org
"MMC") contained in the site means any set of copyrightable works thusg
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 licenseg
published by Creative Commons Corporation, a not-for-profit corporation with ag
principal place of business in San Francisco, California, as well as futureg
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, asg
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, andg
if all works that were first published under this License somewhere other thang
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)g
had no cover texts or invariant sections, and (2) were thus incorporated priorg
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site underg
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMCg
is eligible for relicensing.

